[package]
name = "noted_commons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.19.1"
env_logger = "0.11.1"
log = "0.4"
raw-window-handle = "0.6.0"