[package]
name = "noted_linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noted_commons = { path = "../noted_commons" }
winit = "0.29.10"