[editor]
backspace = "editor::Backspace"
delete = "editor::Delete"
enter = "editor::Enter"
up = "editor::Up"
down = "editor::Down"
left = "editor::Left"
right = "editor::Right"
shift-left = "editor::SelectLeft"
shift-right = "editor::SelectRight"
shift-up = "editor::SelectUp"
shift-down = "editor::SelectDown"
home = "editor::Home"
end = "editor::End"
shift-home = "editor::SelectToStartOfLine"
shift-end = "editor::SelectToEndOfLine"
ctrl-a = "editor::SelectAll"
ctrl-c = "editor::Copy"
ctrl-x = "editor::Cut"
ctrl-v = "editor::Paste"
ctrl-z = "editor::Undo"
ctrl-y = "editor::Redo"
